blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/kolirt/laravel-sitemap?tab=readme-ov-file#laravel-sitemap
    about: Check the documentation for guides and examples.